content from Kikisek
w3c/wai-intro-accessibility pull request #56
Opened 2020-08-26 03:05 UTC by slhenry

getting updated translation.yml included

2020-08-26 17:17 UTC, slhenry commented
From @Kikisek

2020-08-26 17:30 UTC, slhenry commented
@Kikisek  said:
> In the preview, the font (Noto Sans) doesn't seem to be rendering some of the special characters (ř, ž, ů, š, č, ě, ) very well. But when checking the font itself, it seems like the font should handle them just fine. 🤷

Maybe we have to specify Czech version of Noto Sans or something? I can look into it in the next few days...

2020-08-30 19:07 UTC, zmrhaljiri requested changes

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +{% include video-link.html title="Úvodní video pro webovou přístupnost a W3C standardy <em>(4 minuty)</em>" href="https://www.w3.org/WAI/videos/standards-and-benefits.html" src="/content-images/wai-i
I'd replace **Úvodní video pro webovou přístupnost a W3C standardy** with **Video úvod do webové přístupnosti a W3C standardyů** to match (newly proposed) title from https://github.com/w3c/wai-video-standards-and-benefits/pull/69/files

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +Webová přístupnost zahrnuje všechna postižení, která mají vliv na přístup k webu, včetně postiženích:
I'd change **včetně postiženích** to **včetně postižení**

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +-   Pokud chcete zjistit více o tom, jak různá zdravotní postižení ovlivňují používání webu a přečíst si o příkladech lidí s postižením, jak používají web, navštivte [[Jak lidé s postižením používají
I'd keep just **Pokud chcete zjistit více o tom, jak různá zdravotní postižení ovlivňují používání webu, navštivte ...** since the main point is alredy clear from the link title.

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +Při vývoji nebo redesignu webové stránky, zhodnoťte přístupnost na začátku, a pak také během vývoje, abyste identifikovali problémy v přístupnosti co nejdříve, dokud je možné je snadněji opravit. Jed
You can remove comma here: "Při vývoji nebo redesignu webové stránky, zhodnoťte přístupnost na začátku"

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +Při vývoji nebo redesignu webové stránky, zhodnoťte přístupnost na začátku, a pak také během vývoje, abyste identifikovali problémy v přístupnosti co nejdříve, dokud je možné je snadněji opravit. Jed
Vám může pomoci -> Vám mohou pomoci

2020-08-30 19:07 UTC, zmrhaljiri commented on index.cs.md
> +Pokud není poskytnuta textová alternativa obrázku, obrázek není přístupný například pro lidi, kteří nevidí a používají odečítač obrazovky. Ten čte nahlas informace na stránce, včetně textových altern
I'd use the term "čtečka" instead of "odečítač".

2020-08-30 20:20 UTC, Kikisek commented
Thank you for the review! 
Review changes are applied in #57 as I cannot update this branch.

2020-08-31 23:20 UTC, Kikisek approved these changes
Content looks as intended (including review suggestions). Thank you for adding Jiří as contributor!

2020-10-23 22:58 UTC, merged