[IN-PROGRESS] es - Introduction to Web Accessibility
w3c/wai-intro-accessibility pull request #87
Opened 2023-11-25 08:12 UTC by visanju

Applied changes and one typo solved

2023-11-27 22:30 UTC, remibetin commented
Hi @visanju,

Are you still working on this PR or is it ready for review?

2023-12-06 08:50 UTC, cmuncharaz approved these changes

2023-12-06 14:00 UTC, remibetin requested changes
Hi @visanju,

Thank you for this translation update!

Please see my comments in the "Files changed" tab.

There is also a new bullet point missing in the translation: (in "More Info on Accessibility is Important" box)

```
   -   Examples of the benefits of [making audio and video media accessible](/media/av/) is in the section [Benefits to Organizations](/media/av/users-orgs/#benefits).
```

Can you translate this part and add it to the translation?

Thanks!

2023-12-06 14:00 UTC, remibetin commented on content/index.es.md
> +permalink: /fundamentals/accessibility-intro/es   # Add the language shortcode to the end, with no slash at the end. For example /path/to/file/fr
Permalink, ref, changelog and layout attributes have been duplicated (see line 14 to 17 & line 23 to 27).

Please only keep lines 23 to 27.

2023-12-06 14:00 UTC, remibetin commented on content/index.es.md
> +    -   [Cómo cumplir las WCAG (Referencia Rápida)](http://www.w3.org/WAI/WCAG22/quickref/)
```suggestion
    -   [Cómo cumplir las WCAG (Referencia Rápida)](https://www.w3.org/WAI/WCAG22/quickref/)
```

HTTPS is now used in the original version.

2023-12-06 14:00 UTC, remibetin commented on content/index.es.md
> +Las imágenes deben incluir una *[alternativa textual equivalente](http://www.w3.org/TR/UNDERSTANDING-WCAG22/text-equiv.html)* (texto alternativo) en el marcado/código.
```suggestion
Las imágenes deben incluir una *[alternativa textual equivalente](https://www.w3.org/WAI/WCAG22/Understanding/text-alternatives)* (texto alternativo) en el marcado/código.
```
The new URL is https://www.w3.org/WAI/WCAG22/Understanding/text-alternatives

2024-03-07 16:09 UTC, remibetin commented
@visanju Thanks to [your issue](https://github.com/w3c/wai-intro-accessibility/issues/86), we have just slightly updated the original resource. See [this diff file](https://github.com/w3c/wai-intro-accessibility/commit/32277e7db5dd0f36d607cd800da1b0831ba84814#diff-a4f40b84fbcf1a7939d596dca4939bbae6e56c05ad06a62b719b42693a9baf07)

Would you update your translation accordingly?

2024-06-13 23:48 UTC, cmuncharaz commented
I'm trying to push changes (adding a missing bullet point and updating the translation according to the diff file shared above). However, I'm getting an error when pushing.

I think this error could be due to the "Allow edits from maintainers" option deactivated. Could you please make sure this option is checked, @visanju?

2024-06-14 22:36 UTC, merged

2024-06-14 22:39 UTC, remibetin commented
@cmuncharaz Thanks for contributing to this translation! This is greatly appreciated.

I have created a dedicated `es` branch containing @visanju's work. Would you open a new PR to update this branch?

2024-07-09 15:08 UTC, remibetin commented
Hi @cmuncharaz 

Have you had the chance to see my reply? Let me know if I can help!